./utils.sv
../../vsrc/rv32_defines.svh
../../vsrc/rv32_types.svh
../../vsrc/rv32_instr.svh
../../vsrc/rv32_imm_gen.sv
../../vsrc/rv32_decoder.sv
../../vsrc/altera_mf.v
../../vsrc/bram16k.v
../../vsrc/rv32_alu.sv
../../vsrc/rv32_regfile.sv
../../vsrc/rv32_core.sv
../../vsrc/rv32_utils.sv
../../vsrc/rv32_next_pc.sv
./core_tester.sv
